#!/bin/bash

echo "=== 测试产品分类多语言数据保存 ==="
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 重启后端服务:"
echo "   cd /Users/shangxb/fastapi-vue3/nextjs+vue3/youlai-nest"
echo "   npm run start:dev"
echo ""
echo "2. 刷新前端页面 (重要！):"
echo "   按 Ctrl + R 或 Cmd + R 刷新浏览器"
echo "   访问: http://localhost:3000/product/category"
echo ""
echo "3. 打开浏览器开发者工具:"
echo "   - 按 F12 打开开发者工具"
echo "   - 切换到 'Console' 标签页"
echo "   - 切换到 'Network' 标签页"
echo ""
echo "4. 添加产品分类:"
echo "   - 点击 '新增' 按钮"
echo "   - 填写分类名称:"
echo "     * 中文: 测试产品分类"
echo "     * 英文: Test Product Category"
echo "   - 点击 '确定' 保存"
echo ""
echo "5. 收集日志信息:"
echo ""
echo "   A. 前端 Console 日志:"
echo "      - 复制所有以 '[前端]' 开头的日志"
echo ""
echo "   B. 前端 Network 请求:"
echo "      - 在 Network 标签中找到 POST /api/v1/products/categories 请求"
echo "      - 点击该请求"
echo "      - 切换到 'Payload' 或 '请求' 标签"
echo "      - 复制请求体 (Request Body)"
echo ""
echo "   C. 后端日志:"
echo "      - 在后端终端中复制所有以 '[产品分类]' 开头的日志"
echo "      - 包括: [产品分类Controller]、[产品分类] 等"
echo ""
echo "6. 把收集到的日志发送给我分析"
echo ""
echo "=== 预期日志 ==="
echo "前端 Console:"
echo "  [前端] 表单验证结果: true"
echo "  [前端] 准备发送的数据: { parentId: 0, sort: 100, status: 1, langData: {zh: '...', en: '...'} }"
echo "  [前端] 发送创建请求..."
echo ""
echo "前端 Network (Request Body):"
echo "  {"
echo "    "parentId": 0,"
echo "    "sort": 100,"
echo "    "status": 1,"
echo "    "langData": {"
echo "      "zh": "测试产品分类","
echo "      "en": "Test Product Category""
echo "    }"
echo "  }"
echo ""
echo "后端日志:"
echo "  [产品分类Controller] 接收到的请求体: {...}"
echo "  [产品分类] 接收到的DTO: {...}"
echo "  [产品分类] 主表保存成功, ID: 2"
echo "  [产品分类] 开始保存多语言数据: {...}"
echo "  [产品分类] saveCategoryLangData 参数: {...}"
echo "  [产品分类] 过滤后的多语言数据: {...}"
echo "  [产品分类] 准备保存的多语言实体: {...}"
echo "  [产品分类] 多语言数据保存成功"
echo ""
